version: '3'
services:
  khadar:
    image: khadarbasha019/khadarking:latest
    ports:
      - "101:80"
    deploy:
      replicas: 3

  saheen:
    image: khadarbasha019/shaheenqueen:latest
    ports:
      - "102:80"
    deploy:
      replicas: 3

  sana:
    image: khadarbasha019/sanababy:latest
    ports:
      - "103:80"
    deploy:
      replicas: 3

  
