version: '3'
services:
  khadar:
    image: khadarbasha019/khadarking:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  saheen:
    image: khadarbasha019/shaheenqueen:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3

  sana:
    image: khadarbasha019/sanababy:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3

  
